<?php
include_once('widgets/base-widget.php');
include_once('widgets/base-widget_base_product_list.php');
include_once('widgets/base-widget_description.php');
include_once('widgets/base-widget_ordered.php');
include_once('widgets/widget-catalog.php');
include_once('widgets/widget-description.php');
include_once('widgets/widget-list.php');
include_once('widgets/widget-product-brands-info.php');
include_once('widgets/widget-product-list.php');